Jazzmin admin theme
opengisch/qfieldcloud pull request #859
Opened 2024-01-23 12:27 UTC by why-not-try-calmer

2024-01-23 16:15 UTC, suricactus approved these changes
Thanks for contributing this upstream!

Few comments, I know you might not manage to address them yourself:

- [x] Ideally we should not have multiple CSS, if needed we can create `css/admin.css`
- [x] We need to move the favicon to be available in the `core` app

2024-01-23 16:15 UTC, suricactus commented on docker-app/qfieldcloud/settings.py
> +    "custom_css": "css/login.css",
```suggestion
    # Page title. Defaults to `current_admin_site.site_title` if empty.
    "site_title": "QFieldCloud: Admin",
    # Site header title (max 19 chars). Defaults to  `current_admin_site.site_header` if empty.
    "site_header": "QFieldCloud",
    # Brand name (max 19 chars). Defaults to  `current_admin_site.site_header` if empty.
    "site_brand": "QFieldCloud",
    # Favicon filename. Defaults to `site_logo` if empty.
    "site_icon": "favicon.ico",
    # Logo filename.
    "site_logo": "img/opengis_powering_qfc.png",
    # Sign-in form logo filename. Defaults to `site_logo` if empty.
    "login_logo": "img/opengis_powering_qfc.png",
    # Sign-in form welcome text.
    "welcome_sign": "Welcome to QFieldCloud",
    # Copyright on the footer.
    "copyright": "OPENGIS.ch",
    # Additional custom CSS file for the Django Admin pages.
    "custom_css": "css/login.css",
```

2024-01-23 16:15 UTC, suricactus commented on docker-app/qfieldcloud/settings.py
> +    "jazzmin",  # admin theme
```suggestion
    # admin theme
    "jazzmin",
    # django contrib
```

2024-01-23 16:15 UTC, suricactus commented on docker-app/qfieldcloud/settings.py
> +    "custom_css": "css/login.css",
```suggestion
    "custom_css": "css/qfieldcloud.css",
```
Ideally we should only use one CSS file for everything.

2024-01-23 16:15 UTC, suricactus reviewed
Thanks for contributing this upstream!

Few comments, I know you might not manage to address them yourself:

- [ ] Ideally we should not have multiple CSS, if needed we can create `css/admin.css`
- [ ] We need to move the favicon to be available in the `core` app

2024-01-23 16:17 UTC, suricactus requested changes
See my comments above before merging.

2024-01-23 16:18 UTC, why-not-try-calmer commented
On second thought, shouldn't this PR be made against the private repo, where you do have staticfiles?

2024-02-15 11:30 UTC, suricactus approved these changes
Good move!

2024-02-15 14:39 UTC, dddpt commented
Ready for re-review!

2024-02-16 09:30 UTC, suricactus approved these changes
Thank you very much for detecting and fixing untranslated strings in the templates ❤️ .

2024-02-19 09:41 UTC, merged