Restored the ability to create subscriptions with plans
opengisch/qfieldcloud pull request #899
Opened 2024-03-11 09:10 UTC by suricactus

Create:
![image](https://github.com/opengisch/qfieldcloud/assets/2820439/bcfe242e-1a6e-48da-a6e8-62564cbfb27b)
Update:
![image](https://github.com/opengisch/qfieldcloud/assets/2820439/53d44728-a30b-4f6c-8811-4f3d5cad01fc)

Before when creating one cannot select their plan.

2024-03-11 09:10 UTC, duke-nyuki commented
Task linked: [QF-3901 Read the plan field in the Subscriptions, make it read-only for editing](https://app.clickup.com/t/2192114/QF-3901)

2024-03-11 17:08 UTC, faebebin requested changes
Thanks for fixing this :+1: - Important for support I guess.

Just fix the fields reported in the core test failure logs then feel free to merge
some more suggested changes, see related PR...

2024-03-12 07:35 UTC, faebebin approved these changes

2024-03-13 13:04 UTC, suricactus commented
> Thanks for fixing this 👍 - Important for support I guess.
> 
> Just fix the fields reported in the core test failure logs then feel free to merge some more suggested changes, see related PR...

Thanks for spotting, allowed myself to force push the two extra fields to keep the history cleaner. Will manage the merge myself later.

2024-03-13 14:16 UTC, merged