When adding a collaborator via the API, add created_by/updated_by
opengisch/qfieldcloud pull request #982
Opened 2024-07-10 05:28 UTC by suricactus

In addition, prevent attempts to add other `User` subclasses as project
collaborators

2024-07-10 05:28 UTC, duke-nyuki commented
Task linked: [QF-4534 Ensure API endpoints for adding collaborators and members works](https://app.clickup.com/t/2192114/QF-4534)

2024-07-11 04:47 UTC, faebebin requested changes
Looks good

One little cleanup suggestion

else great, thanks

2024-07-11 04:47 UTC, faebebin commented on docker-app/qfieldcloud/core/serializers.py
>      role = serializers.CharField()
```suggestion
```

2024-07-12 11:03 UTC, suricactus commented on docker-app/qfieldcloud/core/serializers.py
>      role = serializers.CharField()
Ah good spot.

2024-07-15 06:12 UTC, faebebin approved these changes
LGTM

just the one linting fix, but else good
thanks

2024-07-15 07:54 UTC, suricactus commented
The linting was fixed on `master`. Thanks!

2024-07-15 07:54 UTC, merged