Use optimized packager by default for new projects
opengisch/QFieldCloud pull request #997
Opened 2024-08-01 14:39 UTC by gounux

Since the `QGIS Core Offline Editing` packager is deprecated, why not use the "Optimized packager" for new project as default ?

![image](https://github.com/user-attachments/assets/93f583c1-8b5a-4254-9c7e-358ac7edb9d4)

2024-08-23 21:53 UTC, suricactus requested changes
Thanks for your contribution! You are right that it is a bit strange why the deprecated one was used as default for quite some time. The reason was to allow test period with the old/new packagers. We have more that positive feedback with the new packager and this change should have happened already a few months ago, but it always slipped from the sprints.

Please use new migrations when changing models instead of changing already existing ones. While it will not change much in this case, it make it harder to follow the evolution of the code and the current behaviour of django might change in the future.

Also please rebase on the latest master and run pre-commit, there are some failures caused by the migration to `ruff` a few months ago: https://github.com/opengisch/qfieldcloud/actions/runs/10525606898/job/29164731554

Your change is more than welcome. Thanks again for contributing upstream!

2024-08-23 21:53 UTC, suricactus commented on docker-app/qfieldcloud/core/migrations/0073_project_packaging_offliner.py
> +                default="pythonmini",
Instead of editing an already existing migration, please create a new migration with this change only.

2024-09-03 16:18 UTC, suricactus commented
Closing due to inactivity. Will open a PR myself.

2024-09-03 16:18 UTC, closed without merging

2024-09-04 06:22 UTC, gounux commented
thanks @suricactus